affairs/admin/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, request, jsonify
from flask.globals import request  
from affairs.admin.forms import Admin, KategoriF, LoginA, ArtikelP, editArtikel, UploadCSv
from affairs import db, app,bcrypt
from affairs.models import admindb, Kategori, Artikel, CustomerPgAir
from flask_login import login_user, logout_user, current_user, login_required 
import os
import csv
import secrets
import json

admingam = Blueprint('admingam', __name__)

def gthumbnail(file_foto):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(file_foto.filename)
    nama_gambar = random_hex + f_ext
    file_foto.save(os.path.join(app.root_path, 'affairs/static/img', nama_gambar))
    return nama_gambar
    
def savecsv(file_csv):
    data = []
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(file_csv.filename)
    nama_csv = random_hex + f_ext
    file_csv.save(os.path.join(app.root_path, 'affairs/static/csv', nama_csv))
    
    with open('affairs/static/csv/' + nama_csv) as file:
        csvfile = csv.DictReader(file)
        for row in csvfile:
          data.append(row)
        return data
        
    

@admingam.route("/")
def home():
    halaman = request.args.get('halaman', 1, type=int)
    daf_ar = Artikel.query.order_by(Artikel.id.desc()).paginate(page=halaman, per_page=3)
    return render_template("index.html", daf_ar=daf_ar)

@admingam.route('/baca_ar/<int:id>')
def baca_ar(id):
    bca = Artikel.query.get_or_404(id)
    return render_template('baca_ar.html', bca=bca)

@admingam.route("/about")
def about():
    return render_template("about.html")

@admingam.route("/contact")
def contact():
    return render_template("contact.html")
 
@admingam.route("/post")
def post():
    return render_template("post.html")
#risno456
@admingam.route("/admin", methods=["GET","POST"])

def admin():
    form = Admin()
    if form.validate_on_submit():
        hash_password = bcrypt.generate_password_hash(form.password.data)
        kelu = admindb(username=form.username.data, email=form.email.data, password=hash_password)
        db.session.add(kelu)
        db.session.commit()
        return redirect(url_for("admingam.home"))
    return render_template("admin.html", form=form)

@admingam.route("/login_adm", methods=["GET","POST"])
def login_adm():
    form=LoginA()
    if form.validate_on_submit():
        cekmail = admindb.query.filter_by(email=form.email.data).first()
        if cekmail and bcrypt.check_password_hash(cekmail.password, form.password.data):
            login_user(cekmail)
            return redirect(url_for("admingam.admin_panel"))
        else:
            print("login salah harap periksa email dan password")
    return render_template("login.html", form=form)

@admingam.route('/logout_adm')
def logout_adm():
    logout_user()
    return redirect(url_for('admingam.home'))

@admingam.route("/tambahkat", methods=["GET","POST"])
@login_required
def tambah_kat():
    form = KategoriF()
    if form.validate_on_submit():
        nama = Kategori(nama=form.nama_kat.data)
        db.session.add(nama)
        db.session.commit()
        return redirect(url_for("admingam.admin"))
    return render_template("kategori.html", form=form)
    
@admingam.route("/tambah_artikel", methods=["GET","POST"])
@login_required
def tambah_artikel():
  form=ArtikelP()
  form.kategori_id.choices = [(str(kategori_id.id), kategori_id.nama) for kategori_id in Kategori.query.all()]
  if form.validate_on_submit():
    random_hex = secrets.token_hex(8)
    gambar = form.thumbnail.data
    _, f_ext = os.path.splitext(gambar.filename)
    nama_gambar = random_hex + f_ext
    gambar.save(os.path.join(app.root_path, 'affairs/static/img', nama_gambar))
    artl = Artikel(judul=form.judul.data, konten=form.konten.data, thumbnail=nama_gambar ,kategori_id=form.kategori_id.data)
    db.session.add(artl)
    db.session.commit()
    return redirect(url_for('admingam.admin_panel'))
  #form.kategori_.choices.insert(0, ('','===pilih kategori==='))
  return render_template("Artikel.html",form=form, title='Tambah Berita')

@admingam.route('/admin_panel')
@login_required
def admin_panel():
    artl = Artikel.query.all()
    return render_template('admin_panel.html', artl=artl, title='Admin Panel')

@admingam.route('/edit_artikel/<int:id>', methods=["GET","POST"])
def edit_artikel(id):
    form=editArtikel()
    ed_a = Artikel.query.get_or_404(id)
    form.kategori_id.choices = [(str(kategori_id.id), kategori_id.nama) for kategori_id in Kategori.query.all()]
    if request.method == "GET":
        form.judul.data = ed_a.judul
        form.konten.data = ed_a.konten
        form.thumbnail.data = ed_a.thumbnail
        form.kategori_id.data = ed_a.kategori_id
    elif form.validate_on_submit():
        if form.thumbnail.data:
            foto = gthumbnail(form.thumbnail.data)
            ed_a.thumbnail = foto
        ed_a.judul = form.judul.data
        ed_a.konten = form.konten.data
        ed_a.kategori_id = form.kategori_id.data
        db.session.commit()
        return redirect(url_for('admingam.admin_panel'))
    return render_template("edit_artikel.html", form=form, title='Edit Berita')

@admingam.route("/hapus_ar/<int:id>",  methods=["POST"])
@login_required
def hapus_ar(id):
    art = Artikel.query.get_or_404(id)
    if request.method == "POST":
        db.session.delete(art)
        db.session.commit()
        return redirect(url_for('admingam.admin_panel'))
    return redirect(url_for('admingam.admin_panel'))

@admingam.route('/csvupload', methods=["GET","POST"])
@login_required
def csvupload():
    return render_template('upload_csv.html')



@admingam.route("/displaycsv",  methods=["GET","POST"])
@login_required
def displaycsv():
    data = []
    form = UploadCSv()
    if form.validate_on_submit():
      fcsv = savecsv(form.csvField.data)
      cus = CustomerPgAir(csv_field=fcsv)
      db.session.add(cus)
      db.session.commit()
      return redirect(url_for('admingam.home'))
    return render_template('displayfile.html', form=form, title="upload file")
    
@admingam.route('/lamanrek')
def lamanrek():
    rek = CustomerPgAir.query.all()
    return render_template('lamanrek.html', rek=rek,title='Daftar Rekening Bulanan')
            
@admingam.route('/hapusrek/<int:id>')
@login_required
def hapusrek(id):
    hps = CustomerPgAir.query.get_or_404(id)
    db.session.delete(hps)
    db.session.commit()
    return redirect(url_for('admingam.home'))            

@admingam.route('/lihatrek/<int:id>')
def lihatrek(id):
    rek = CustomerPgAir.query.filter_by(id=id).all()

    return render_template('lihatrek.html', rek=rek, title="tabel daftar")  

affairs/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>About</title>

  <!-- Bootstrap core CSS -->
  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="../static/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{current_user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">               
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a> 
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah artikel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin')}}">Laman daftar</a>
                <a class="dropdown-item" href="{{url_for('admingam.logout_adm')}}">Logout</a>              
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admingam.login_adm')}}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="../static/vendor/jquery/jquery.min.js"></script>
  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="../static/js/clean-blog.min.js"></script>

</body>

</html>

affairs/templates/admin_panel.html
{% extends 'layout.html' %} 

{% block kategori %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{current_user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">               
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a> 
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah artikel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin_panel')}}">Admin Panel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin')}}">Logout</a>              
            </div>
        </li>
          
        </ul>
      </div>
    </div>
</nav>

<div class="container" style="margin-top: 10%;">
    <div class="row">
        {% for ar in artl %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{url_for('static', filename='img/' + ar.thumbnail)}}" alt="{{ar.judul}}" class="card-img-top">
                <div class="card-body"></div>
                <h5 class="card-title">{{ar.judul}}</h5>
                <p class="card-text">{{ar.konten | truncate(50)|striptags()}}</p>
                <div class="card-footer">
                    <a href="{{url_for('admingam.edit_artikel', id=ar.id)}}" class=" float-left btn btn-sm btn-primary">edit</a><button type="button" class="float-right btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal-{{ar.id}}">
                      H
                    </button>
                    
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal-{{ar.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ar.judul}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <span class="text-danger"> are you sure to delete this brand {{ar.judul}}</span>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                <form action="{{url_for('admingam.hapus_ar', id=ar.id)}}" method="POST">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <hr>
    </div>
</div>
{% endblock kategori %}

affairs/templates/displayfile.html
{% extends 'layout.html' %}

{% block kategori %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{current_user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">               
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a> 
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah artikel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin_panel')}}">Admin Panel</a>
                <a class="dropdown-item" href="{{url_for('admingam.logout_adm')}}">Logout</a>              
            </div>
        </li>
          
        </ul>
      </div>
    </div>
</nav>

<div class="container" style="margin-top: 25%;">
    <form action="/displaycsv" method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}

            <div class="form-group">

                
                {%if form.csvField.errors%}
                    {{form.csvField(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.csvField.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.csvField(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
              {{form.submit(class="btn btn-sm btn-success")}}
            </div>
    </form>
    
</div>

{% endblock kategori %}

affairs/templates/edit_artikel.html
{% extends 'layout.html' %}



{%block kategori%}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{current_user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">               
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a> 
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah artikel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin_panel')}}">Admin Panel</a>
                <a class="dropdown-item" href="{{url_for('admingam.logout_adm')}}">Logout</a>              
            </div>
        </li>
          
        </ul>
      </div>
    </div>
</nav>
<div class="col-md-2" style="margin-top:10%"></div>
<div class="col-md-8 mt-5">
    <div class="container">
        <h2 class="text-center">edit artikel</h2>
        
        
        <form action="" method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            <div class="form-group">
                
                {%if form.judul.errors%}
                    {{form.judul(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.judul.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.judul(class="form-control")}}
                {% endif %}
            </div>
            <div class="form-group">
              {% if form.konten.errors %}
                  {{form.konten(class="form-control is-invalid")}}
                    {% for error in form.konten.errors %}
                      <div class="invalid-feedback">
                        {{error}}
                      </div>
                      {%endfor%}
              {%else%}      
               {{form.konten.label()}}
               {{form.konten(class="form-control")}}
              {%endif%}
            </div>
              <div class="form-group">
              {% if form.kategori_id.errors %}
                  {{form.kategori_id(class="form-control is-invalid")}}
                    {% for error in form.kategori_id.errors %}
                      <div class="invalid-feedback">
                        {{error}}
                      </div>
                      {%endfor%}
              {%else%}  
              {{form.kategori_id.label()}}

               {{form.kategori_id(class="form-control")}}

              {%endif%}
            </div>
          <div class="form-group">
            {% if form.thumbnail.errors %}
            
            {{form.thumbnail(class="form-control is-invalid")}}
            {% for error in form.thumbnail.errors %}
              <div class="invalid-feedback">
                {{error}}
              </div>
            {%endfor%}
      {%else%}      
          {{form.thumbnail.label()}}
          {{form.thumbnail(class="form-control")}}
      {%endif%}
    </div>
   
            {{form.submit(class="btn btn-sm btn-primary")}}
        </form>
    </div>
    </div>
<div class="col-md-2"></div>

{{ ckeditor.load() }}
{{ ckeditor.config(name="konten") }}
{%endblock kategori%} 

affairs/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Kelurahan Afa-Afa</title>

  <!-- Bootstrap core CSS -->
  <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link rel="icon" type="image/png" sizes="16x16"  href="../static/img/toga.png">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#ffffff">
  <!-- Custom fonts for this template -->
  <link href="../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="../static/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{current_user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">               
                <a class="dropdown-item" href="{{url_for('admingam.tambah_kat')}}">Tambah Kategori</a> 
                <a class="dropdown-item" href="{{url_for('admingam.tambah_artikel')}}">Tambah artikel</a>
                <a class="dropdown-item" href="{{url_for('admingam.admin_panel')}}">Admin Panel</a>
                <a class="dropdown-item" href="{{url_for('admingam.logout_adm')}}">Logout</a>              
            </div>
          </li>
          {% else %}  
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admingam.login_adm')}}">Login</a>
          </li>
        {% endif %}  
        </ul>
      </div>
    </div>
  </nav>
  {%block content%}
  {%endblock content%}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../static/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for df in daf_ar.items %}
        <div class="post-preview">
          <a href="{{url_for('admingam.baca_ar', id=df.id)}}">
            <h2 class="post-title">
             {{df.judul}}
            </h2>
            <h3 class="post-subtitle">
              {{df.konten | truncate(50) | striptags()}}
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            {{df.tgl_post.strftime('%B %d, %Y')}}</p>
        </div>
        
        <hr>
        {% endfor %}
        
        <!-- Pager -->
        <div class="clearfix">
          {% if daf_ar.has_prev %}
          <a class="btn btn-primary float-right " href="{{url_for('admingam.home', halaman=daf_ar.prev_num)}}">&rarr; Prev</a>
          {% endif %}
          {% if daf_ar.has_next %}
          <a class="btn btn-primary float-left" href="{{url_for('admingam.home', halaman=daf_ar.next_num)}}">Next  &larr; </a>
          {% endif %}
          
        </div>
        
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="../static/vendor/jquery/jquery.min.js"></script>
  <script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="../static/js/clean-blog.min.js"></script>

</body>

</html>